Feature/next steps
KitchenStories/home-connect-android pull request #6
Opened 2021-02-05 08:56 UTC by AparnaPattathil

2021-02-05 10:32 UTC, dominikgold approved these changes

2021-02-08 09:13 UTC, falkorichter requested changes
let´s wait until the feature is completely done and merge it then

2021-02-08 09:13 UTC, falkorichter commented on home-connect/build.gradle
> +//apply plugin: 'com.github.dcendents.android-maven'
this should not be on develop - it is only for the submodule based integration that was setup for quicker iteration

2021-02-22 08:17 UTC, falkorichter commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
we should ignore the .idea folder and remove the file from version control

2021-09-10 08:46 UTC, merged